version: "3"
services:
  db:
    image: postgres:14.2
    container_name: db
    restart: always
    environment:
      # default postgresql admin
      POSTGRES_PASSWORD: "${POSTGRESQL_PASSWORD}"
      # default postgresql database that also will be created
      POSTGRES_DB: "${POSTGRESQL_DEFAULT_DB}"
    ports:
      - "${POSTGRESQL_EXPOSED_PORT}:5432"
    volumes:
      # mount the database initialization script
      - ./init/postgresql/:/docker-entrypoint-initdb.d/
      # mount permament storage so we can backup our database
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.5
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_USER}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
    ports:
      - "${PGADMIN_EXPOSED_PORT}:80"
    volumes:
      - pgadmin-data:/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
